# Generated by Django 6.0.4 on 2026-05-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_options_portfolio_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link (Opcional)'),
        ),
    ]
